name: Publish Nuget

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # This line enables manual dispatch

jobs:
  build:
    environment:
      name: production
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Publish
      run: dotnet publish -c Release

    - name: Copy Readme
      run: cp README.md ./Formula.SimpleRepo/README.md

    - name: Pack
      run: dotnet pack

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
